# Generated by Django 5.2.3 on 2025-06-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruangan', models.CharField(max_length=100, unique=True)),
                ('gedung', models.CharField(max_length=50)),
                ('lantai', models.IntegerField()),
                ('kapasitas', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mata_kuliah', models.CharField(max_length=200)),
                ('nama_dosen', models.CharField(max_length=200)),
                ('hari', models.CharField(max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal.ruangan')),
            ],
        ),
    ]
