# Generated by Django 5.2.1 on 2025-06-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
    ]
